Fix issues with PHPCS in `duster fix`, add Pint rule

diff --git a/bin/actions/fix-phpcs b/bin/actions/fix-phpcs
--- a/bin/actions/fix-phpcs
+++ b/bin/actions/fix-phpcs
@@ -3,21 +3,12 @@
 if [[ -f "./.phpcs.xml" ]] || [[ -f "./phpcs.xml" ]] || [[ -f "./.phpcs.xml.dist" ]] || [[ -f "./phpcs.xml.dist" ]]; then
   vendor/bin/phpcbf --config-set installed_paths ../../tightenco/duster/standards/Tighten > /dev/null
   vendor/bin/phpcbf
-
   vendor/bin/phpcs > /dev/null
-  if [ $? -ne 0 ]; then
-    echo "PHP Code_Sniffer found errors that cannot be fixed automatically. Run 'duster phpcs' to view them."
-    exit 1
-  else
-    exit 0
-  fi
 else
   vendor/bin/phpcbf --standard=vendor/tightenco/duster/standards/Tighten/ app config database public resources routes tests
   vendor/bin/phpcs --standard=vendor/tightenco/duster/standards/Tighten/ app config database public resources routes tests > /dev/null
-  if [ $? -ne 0 ]; then
-    echo "PHP Code_Sniffer found errors that cannot be fixed automatically. Run 'duster phpcs' to view them."
-    exit 1
-  else
-    exit 0
-  fi
+fi
+
+if [ $? -ne 0 ]; then
+  echo -e "${RED}WARNING${NOCOLOR} PHP Code_Sniffer found errors that cannot be fixed automatically. Run 'duster phpcs' to view them.\n"
 fi
